[workspace]
members = [
    "01_report_repair",
    "02_password_philosophy",
    "03_toboggan_trajectory",
    "04_passport_processing",
    "05_binary_boarding",
    "06_custom_customs",
    "07_handy_haversacks",
    "08_handheld_gaming",
]
